### ISSUE TITLE
User/Coalition report

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/sjya-backoffice#16]
there are 10 sectors listed.  Is the list of sectors dynamic or static?  If static need to add Faith Based and Media. If dynamic need to make sure it is listing all sectors.

Also need to be able to view the individual coalition members by clicking in the number of participants from the report.  So who are the 8 business sector members?

**Comment by reed** [comment]
That report only shows sectors that have members.  There already is a Media sector and a "Religious/Fraternal" sector, but they don't have members.

**Comment by jamiemiller1486** [comment]
I changed a user  and an organization to media and it did not change.

Sent from my iPad

On Jan 28, 2015, at 5:37 PM, Nick Reed <notifications@github.com<mailto:notifications@github.com>> wrote:


That report only shows sectors that have members. There already is a Media sector and a "Religious/Fraternal" sector, but they don't have members.

**Comment by reed** [comment]
What do you mean you changed a user to media?  You did change an organization to media, but that organization has no members.

**Comment by jamiemiller1486** [comment]
They say there should be a media member showing [http://sjya.backofficeapps.com/users/18] Nadia Thacker.  She is currently listed under http://sjya.backofficeapps.com/users?org=44 American Business and Technology University.

She has changed employers.  To test, I changed her to http://sjya.backofficeapps.com/users?org=10 News Press Now., which is Media.  The report does not change.

So maybe she is not listed in any activity as a coalition member?

Another reason why we need the Coalition Members field linked to show those users.

**Comment by reed** [comment]
You didn't clear the cache, so the report wasn't updated.

**Comment by jamiemiller1486** [comment]
ok

Jamie A Miller
Director of Research
LAN Resources, LLC
816-238-5596
www.lanresourcesllc.com<http://www.lanresourcesllc.com>
