### ISSUE TITLE
Activities list view changes

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/sjya-backoffice#17]
need to add Activity # as first field
Remove "Completed by"
Remove "Completed for"
Add "Activity type" with ability to filter activities by clicking on type like on ASM budgets
Show "Description" instead of making click on the . . .
  
Add date range to do a quick filter.

**Comment by reed** [comment]
Activities don't have numbers.  They have IDs, but those are only important to the system.  It is considered bad practice (and a mild security issue) to display IDs to the user like this.  One problem is that it implies that these IDs are permanent, when they are in fact not.

**Comment by jamiemiller1486** [comment]
http://sjya.backofficeapps.com/rf/activities/63

She is accessing the activities via the Activity Summary report and getting the link above.  It has Activity #63 as the heading, which she is using as a reference.  She then wants to quickly get back to that activity from the http://sjya.backofficeapps.com/rf/activities page
