### ISSUE TITLE
Activity Summary Report

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/sjya-backoffice#19]
http://sjya.backofficeapps.com/reports/activity-summary

Need to add the Total # of Impressions to the report between Total Participants and Volunteer Hours
Need to add the Total In Kind amount to the report

These can go on the main report, or the 2ndary report that shows when you click on the # of Activities for an activity type.

**Comment by reed** [comment]
The "Total In Kind" field is not a numeric field.  I don't know how you expect me to add them together.

**Comment by jamiemiller1486** [comment]
So if they are needing to see total in-kind as a whole, or by sector, what would our options be?

**Comment by reed** [comment]
It doesn't seem possible.  You can't combine "Free Radio Spots", "10 miles", and "$500".

**Comment by jamiemiller1486** [comment]
What if we just create a new report Called “in kind” that allows them to select a date range.  It then shows all of the in-kind entries by sector for that range.

**Comment by reed** [comment]
If that's what you want, I guess that's what I'll do.

**Comment by reed** [comment]
Would it be enough to just include the in-kind amount for each activity on the secondary report that shows when you click on the number of activities?  Like this:

![image](https://cloud.githubusercontent.com/assets/672142/6010422/e2bcc6ac-aaf7-11e4-9ab3-5399394215e5.png)

**Comment by jamiemiller1486** [comment]
Yes.  Lets start with that.
